set(_CATKIN_CURRENT_PACKAGE "receive_image")
set(receive_image_VERSION "0.0.0")
set(receive_image_MAINTAINER "hossein <hossein@todo.todo>")
set(receive_image_PACKAGE_FORMAT "2")
set(receive_image_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(receive_image_BUILD_EXPORT_DEPENDS )
set(receive_image_BUILDTOOL_DEPENDS "catkin")
set(receive_image_BUILDTOOL_EXPORT_DEPENDS )
set(receive_image_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(receive_image_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(receive_image_TEST_DEPENDS )
set(receive_image_DOC_DEPENDS )
set(receive_image_URL_WEBSITE "")
set(receive_image_URL_BUGTRACKER "")
set(receive_image_URL_REPOSITORY "")
set(receive_image_DEPRECATED "")